import type { Metadata } from "next";

import { ChakraProvider, Container } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "i18next JSON Inspector",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <Container display="flex" alignItems="center" justifyContent="center">
            {children}
          </Container>
        </ChakraProvider>
      </body>
    </html>
  );
}
